eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769

spring:
  application:
    name: gateway-server
zuul:
  routes:
    api-hlwl:
      path: /hlwl/**
      serviceId: hlwl-app
    api-dzdj:
      path: /dzdj/**
      serviceId: dzdj-service
