server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
      name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/martian-chao/springcloud_config
          searchPaths:
          username:
          password:
      label: master